### ISSUE TITLE
 Problem with multiple levels

### ISSUE THREAD

**Issue by valentinafratini** [webgeodatavore/ol3-search-layer#6]
Hello,
I used ol-search-layer to insert in my openstreetmap a search box that could search for my layers. But in my map I have separate layers of vectors to give each one a different color and not a single layer as in the example above. If I insert into searchLayer more layers, these are not read. I also tried to make a group of layers but it does not work equally. How can I do? 
I attach below the code:

                     var vector1 = new ol.layer.Vector({
				title: 'Blu',
				source: new ol.source.Vector({
					format: new ol.format.GeoJSON(),
					url: 'http://localhost/joggo_wp/percorso1.geojson'
				}),
				style: new ol.style.Style({
					stroke: new ol.style.Stroke({
						color: '#0051FF',
						width: 2.5
					})
				}),
				
			});
			
			var vector2 = new ol.layer.Vector({
				title: 'Rosso',
				source: new ol.source.Vector({
					format: new ol.format.GeoJSON(),
					url: 'http://localhost/joggo_wp/percorso2.geojson',
				}),
				style: new ol.style.Style({
					stroke: new ol.style.Stroke({
						color: '#ff0010',
						width: 2.5
					})
				}),
			});
			
			var vector3 = new ol.layer.Vector({
				title: 'Verde',
				source: new ol.source.Vector({
					format: new ol.format.GeoJSON(),
					url: 'http://localhost/joggo_wp/percorso3.geojson'
				}),
				style: new ol.style.Style({
					stroke: new ol.style.Stroke({
						color: '#36c100',
						width: 2.5
				}),
					})
								
			});
			
			var vector4 = new ol.layer.Vector({
				title: 'Rosa',
				source: new ol.source.Vector({
					format: new ol.format.GeoJSON(),
					url: 'http://localhost/joggo_wp/percorso4.geojson'
				}),
				style: new ol.style.Style({
					stroke: new ol.style.Stroke({
						color: '#ef00d3',
						width: 2.5
					})
				}),
								
			});
			
			var vector5 = new ol.layer.Vector({
				title: 'Azzurro',
				source: new ol.source.Vector({
					format: new ol.format.GeoJSON(),
					url: 'http://localhost/joggo_wp/percorso5.geojson'
				}),
				style: new ol.style.Style({
					stroke: new ol.style.Stroke({
						color: '#00d8d8',
						width: 2.5
					})
				}),
				
								
			});
			
			/*var gruppo_vectors = new ol.layer.Group({
				title: 'Percorsi:',
				layers: [
					vector1,
					vector2,
					vector3,
					vector4,
					vector5,
				],
			});*/
			
			var map = new ol.Map({
				layers: [
					new ol.layer.Tile({
						source: new ol.source.OSM({
							attributions: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, '+'Tiles courtesy of <a href="http://hot.openstreetmap.org/" target="_blank">Humanitarian OpenStreetMap Team</a>',
							}),
					}),
					vector1,
					vector2,
					vector3,
					vector4,
					vector5,
				],
				target: 'map',
				view: new ol.View({
					center: ol.proj.transform([11.260626699999989, 43.7578609], 'EPSG:4326', 'EPSG:3857'),
					zoom: 13.70
				})
			});
			
			var searchLayer = new ol.SearchLayer({
			  layer: [
			  	vector1,
				vector2,
				vector3,
				vector4,
				vector5,
				],
			  colName: 'NOME',
			  zoom: 10,
			  collapsed: true,
			  map: map
			});
			
			map.addControl(searchLayer);

Thank you very much, 
Valentina Fratini.

**Comment by ThomasG77** [comment]
The plugin was never intended for this purpose. It would not work and I do not plan to make changes on my own. I accept pull request if any.

Although, it will not solve you issue, for maintainability purpose, you should get the overall GeoJSON in one time. Then, you can dispatch each category in a new intermediate source and make your layers consume them. You will have to maintain only one datasource instead of a GeoJSON per category.
